#!/USR/BIN/PYTHON3
"""
FETCHES HTTPS://INTRANET.HBTN.IO/STATUS
"""
IF __NAME__ == '__MAIN__':
    IMPORT REQUESTS
    R = REQUESTS.GET('HTTPS://INTRANET.HBTN.IO/STATUS')
    TEXT = R.TEXT
    PRINT("BODY RESPONSE:")
    PRINT("\T- TYPE: {}".FORMAT(TYPE(TEXT)))
    PRINT("\T- CONTENT: {}".FORMAT(TEXT))
